### ISSUE TITLE
Xdebug

### ISSUE THREAD

**Issue by asaladino** [shameerc/docker-php7#2]
Nice environment. I'm trying to enable xdebug with phpstorm. Have you had any success getting xdebug working?

**Comment by shameerc** [comment]
Thanks! I haven't tried it yet :(

**Comment by asaladino** [comment]
I'll keep trying. I think my issue is a port collision with fpm and a bug in docker for macOS not allowing xdebug.remote_connect_back.

**Comment by shameerc** [comment]
Cool, let us know if you are able to get it working :)
